apiVersion: sparkoperator.hpe.com/v1beta2
kind: SparkApplication
metadata:
  creationTimestamp: 2023-09-08T01:22:58Z
  generation: 1
  labels:
    hpe-ezua/app: spark
    hpe-ezua/type: app-service-user
  name: test_imguru-t1-cus-info-test
  namespace: spark
  resourceVersion: "6175641"
  uid: 98d6774b-115d-45d1-9cb3-d3f50bb07b72
spec:
  driver:
    coreLimit: "1"
    cores: 1
    labels:
      version: 3.4.0
    memory: 4G
    serviceAccount: hpe-spark
    volumeMounts:
      - mountPath: /mounts/imguru-volume
        name: imguru-volume
      - mountPath: /mounts/shared-volume
        name: shared-volume
      - mountPath: /opt/mapr/spark/sparkhs-eventlog-storage
        name: sparkhs-eventlog-storage
  executor:
    coreLimit: "1"
    cores: 1
    instances: 1
    labels:
      version: 3.4.0
    memory: 4G
    serviceAccount: hpe-spark
    volumeMounts:
      - mountPath: /mounts/imguru-volume
        name: imguru-volume
      - mountPath: /mounts/shared-volume
        name: shared-volume
  image: gcr.io/mapr-252711/spark-py-3.4.0:v3.4.0
  imagePullPolicy: Always
  imagePullSecrets:
    - imagepull
  mainApplicationFile: local:///mounts/imguru-volume/spark/t1_cus_infotest.py
  mode: cluster
  restartPolicy:
    type: Never
  sparkConf:
    spark.eventLog.dir: file:///opt/mapr/spark/sparkhs-eventlog-storage
    spark.eventLog.enabled: "true"
    spark.executorEnv.PRESTO_ACCESS_TOKEN: eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJxS0hXWWw5cGVONlNxQ25WeGlZM0tGaTIwaHpkb0dRNFpJWTd3NUhITXFvIn0.eyJleHAiOjE2OTQ3MzY3NjQsImlhdCI6MTY5NDEzMjAwMiwiYXV0aF90aW1lIjoxNjk0MTMxOTY0LCJqdGkiOiJkYzYxMWIyOC0yYTEzLTQwMTItYThhNy05NGExNDQ1MTk2NmUiLCJpc3MiOiJodHRwczovL2tleWNsb2FrLmV6bWVyYWwuZXRldmVycy5jb20vcmVhbG1zL1VBIiwiYXVkIjoidWEiLCJzdWIiOiI3NDkzYzQ5OC0yOWE5LTQ4MjgtOTUyNi0xYTgwMGRkN2UwMWUiLCJ0eXAiOiJJRCIsImF6cCI6InVhIiwibm9uY2UiOiJGVFF0ZEpWVFNYQW1PbVlMM0RKLWd0Ym9rT0xqT0RoejlQa004am5GMG9FIiwic2Vzc2lvbl9zdGF0ZSI6ImU2MjRlNzE3LWM3NzItNDczNy1iZDhlLTA3ZTRiODA3NmQxNSIsImF0X2hhc2giOiJJZHY1OXQ4SEZfNzVTaE44a09qYTl3IiwiYWNyIjoiMCIsInNpZCI6ImU2MjRlNzE3LWM3NzItNDczNy1iZDhlLTA3ZTRiODA3NmQxNSIsImVtYWlsX3ZlcmlmaWVkIjpmYWxzZSwibmFtZSI6ImltZ3VydSBpbWd1cnUiLCJncm91cHMiOlsidWEtZW5hYmxlZCIsIm9mZmxpbmVfYWNjZXNzIiwiYWRtaW4iLCJ1bWFfYXV0aG9yaXphdGlvbiIsImRlZmF1bHQtcm9sZXMtdWEiXSwicHJlZmVycmVkX3VzZXJuYW1lIjoiaW1ndXJ1IiwiZ2l2ZW5fbmFtZSI6ImltZ3VydSIsInBvc2l4X3VzZXJuYW1lIjoiaW1ndXJ1IiwiZmFtaWx5X25hbWUiOiJpbWd1cnUiLCJlbWFpbCI6ImltZ3VydUBpbWd1cnUuY29tIn0.DGuAFgTAW8SQz0mVoQPUt7rg83CZToojgd5FGIrPWPQ3l0A3Xkqh2NSXijx9hy3jR6HBRpEcfCbMRftXP_fNRSPgN7F2ZSqQL7111MkAS-RuP1ePwbwHwI2n4uKPk9RZ5s2PSRsz47zu7zMOY0SKCNxmuxrJaUcD0pmndXrynJBzptQjspN1b03herHuunmFkPL61NSDQlnbCJ-s-ymDsCNC59kVqfb7oDkfOIFH7fSs-sK4_9bCBjKDTQS2rj_DRiy4qzk47fdlnOVObS64iKnFCAJqfULnMMf8hIoNK2TqWUWRLG8ZTiHzc-jIskxs5K05pQ5xBKM5_PN-Thju2Q
    spark.kubernetes.driverEnv.PRESTO_ACCESS_TOKEN: eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJxS0hXWWw5cGVONlNxQ25WeGlZM0tGaTIwaHpkb0dRNFpJWTd3NUhITXFvIn0.eyJleHAiOjE2OTQ3MzY3NjQsImlhdCI6MTY5NDEzMjAwMiwiYXV0aF90aW1lIjoxNjk0MTMxOTY0LCJqdGkiOiJkYzYxMWIyOC0yYTEzLTQwMTItYThhNy05NGExNDQ1MTk2NmUiLCJpc3MiOiJodHRwczovL2tleWNsb2FrLmV6bWVyYWwuZXRldmVycy5jb20vcmVhbG1zL1VBIiwiYXVkIjoidWEiLCJzdWIiOiI3NDkzYzQ5OC0yOWE5LTQ4MjgtOTUyNi0xYTgwMGRkN2UwMWUiLCJ0eXAiOiJJRCIsImF6cCI6InVhIiwibm9uY2UiOiJGVFF0ZEpWVFNYQW1PbVlMM0RKLWd0Ym9rT0xqT0RoejlQa004am5GMG9FIiwic2Vzc2lvbl9zdGF0ZSI6ImU2MjRlNzE3LWM3NzItNDczNy1iZDhlLTA3ZTRiODA3NmQxNSIsImF0X2hhc2giOiJJZHY1OXQ4SEZfNzVTaE44a09qYTl3IiwiYWNyIjoiMCIsInNpZCI6ImU2MjRlNzE3LWM3NzItNDczNy1iZDhlLTA3ZTRiODA3NmQxNSIsImVtYWlsX3ZlcmlmaWVkIjpmYWxzZSwibmFtZSI6ImltZ3VydSBpbWd1cnUiLCJncm91cHMiOlsidWEtZW5hYmxlZCIsIm9mZmxpbmVfYWNjZXNzIiwiYWRtaW4iLCJ1bWFfYXV0aG9yaXphdGlvbiIsImRlZmF1bHQtcm9sZXMtdWEiXSwicHJlZmVycmVkX3VzZXJuYW1lIjoiaW1ndXJ1IiwiZ2l2ZW5fbmFtZSI6ImltZ3VydSIsInBvc2l4X3VzZXJuYW1lIjoiaW1ndXJ1IiwiZmFtaWx5X25hbWUiOiJpbWd1cnUiLCJlbWFpbCI6ImltZ3VydUBpbWd1cnUuY29tIn0.DGuAFgTAW8SQz0mVoQPUt7rg83CZToojgd5FGIrPWPQ3l0A3Xkqh2NSXijx9hy3jR6HBRpEcfCbMRftXP_fNRSPgN7F2ZSqQL7111MkAS-RuP1ePwbwHwI2n4uKPk9RZ5s2PSRsz47zu7zMOY0SKCNxmuxrJaUcD0pmndXrynJBzptQjspN1b03herHuunmFkPL61NSDQlnbCJ-s-ymDsCNC59kVqfb7oDkfOIFH7fSs-sK4_9bCBjKDTQS2rj_DRiy4qzk47fdlnOVObS64iKnFCAJqfULnMMf8hIoNK2TqWUWRLG8ZTiHzc-jIskxs5K05pQ5xBKM5_PN-Thju2Q
    spark.kubernetes.driverEnv.SPARK_USER: imguru
    spark.kubernetes.executorEnv.SPARK_USER: imguru
    spark.mapr.user.secret: hpe-autotix-generated-secret-artpah
    spark.mapr.user.secret.autogen: "true"
  sparkVersion: 3.4.0
  type: Python
  volumes:
    - name: imguru-volume
      persistentVolumeClaim:
        claimName: imguru-spark-pvc
    - name: shared-volume
      persistentVolumeClaim:
        claimName: kubeflow-shared-pvc
    - name: sparkhs-eventlog-storage
      persistentVolumeClaim:
        claimName: sparkhs-pvc
